
###
GET http://localhost:8080/material

###
POST http://localhost:8080/material
Content-Type: application/json

{
  "idFornecedor": 1,
  "descricao": "Mesa Vermelha",
  "unidade": "METRO_QUADRADO",
  "custo": 256.89,
  "codigoFabricante": "XX098"
}


###
GET http://localhost:8080/material/2

###
DELETE http://localhost:8080/material/1

###
PUT http://localhost:8080/material/2
Content-Type: application/json

{
  "descricao": "Mesa ROXA",
  "unidade": "METRO",
  "custo": 0.99,
  "codigoFabricante": "YY098"
}
