###
GET http://localhost:8080/ordem-venda

###
GET http://localhost:8080/ordem-venda/2

###
POST http://localhost:8080/ordem-venda
Content-Type: application/json

{
  "idCliente": 1,
  "dataEntrega": "2023-10-25",
  "logradouro": "Av. Interlagos",
  "numero": "132",
  "bairro": "interlagos",
  "estado": "SP",
  "cep": "CEP",
  "informacoesAdicionais": "info adc",
  "detalhes": [
    {
      "idProduto": 1,
      "quantidade": 1,
      "desconto": 0
    }
  ]
}

###
PUT http://localhost:8080/ordem-venda/8
Content-Type: application/json

{
  "idCliente": 1,
  "dataEntrega": "2023-10-01",
  "logradouro": "Av. Interlagos",
  "numero": "132",
  "bairro": "interlagossssss",
  "estado": "SP",
  "cep": "18200000",
  "informacoesAdicionais": "....",
  "detalhes": [
    {
      "idProduto": 1,
      "quantidade": 2,
      "desconto": 0
    }
  ]
}

###
DELETE http://localhost:8080/ordem-venda/8
