###
POST http://localhost:8080/produto
Content-Type: application/json

{
  "descricao": "Camiseta 9999_1",
  "preco": 500,
  "detalhes": [
    {
      "idMaterial": 1,
      "quantidade": 2

    },
    {
      "idMaterial": 1,
      "quantidade": 3

    }
  ]
}

###
GET http://localhost:8080/produto

###
PUT http://localhost:8080/produto/2
Content-Type: application/json

{
  "descricao": "Camiseta 1",
  "preco": 52.99,
  "detalhes": [
    {
      "idMaterial": 1,
      "quantidade": 88.99

    }
  ]
}

###
DELETE http://localhost:8080/produto/2