###
POST http://localhost:8080/produto
Content-Type: application/json

{
  "descricao": "Camiseta um novo produto",
  "preco": 150,
  "detalhes": [
    {
      "idMaterial": 1,
      "quantidade": 1

    },
    {
      "idMaterial": 2,
      "quantidade": 2

    }
  ]
}

###
GET http://localhost:8080/produto

###
GET http://localhost:8080/produto/3

###
PUT http://localhost:8080/produto/5
Content-Type: application/json

{
  "descricao": "Camiseta agora é velho",
  "preco": 52.99,
  "detalhes": [
    {
      "idMaterial": 2,
      "quantidade": 5

    }
  ]
}

###
DELETE http://localhost:8080/produto/5