package br.com.exaltasamba.enterprisechallenge.domain.material;

public enum TipoUnidade {

    BARRA, BLOCO,BOBINA, CENTO, CONJUNTO, CENTIMETRO_QUADRADO, CAIXA,
    DUZIA, FOLHA, FRASCO, GALAO, GRAMA, JOGO, KILOGRAMA, LATA, LITRO,
    MILIMETRO, METRO, METRO_QUADRADO, METROS_CUBICOS, PAR, PECA, PACOTE,
    ROLO,SACO,SERVICO,TALAO,TAMBOR,TONELADA,TUBO;

    }
